# Generated by Django 5.2.17 on 2026-09-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='theme_accent',
            field=models.CharField(default='#00E5D0', max_length=7, verbose_name='Accent'),
        ),
        migrations.AddField(
            model_name='event',
            name='theme_ground',
            field=models.CharField(default='#080C18', max_length=7, verbose_name='Background'),
        ),
        migrations.AddField(
            model_name='event',
            name='theme_ink',
            field=models.CharField(default='#E9EEFF', max_length=7, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='event',
            name='theme_signal',
            field=models.CharField(default='#FF3D6E', help_text='Warnings and downward movement', max_length=7, verbose_name='Signal'),
        ),
    ]
