# Generated by Django 5.2.17 on 2026-09-26 18:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Not started'), ('in_progress', 'In progress'), ('submitted', 'Submitted')], db_index=True, default='pending', max_length=12)),
                ('comment', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.project')),
            ],
        ),
        migrations.CreateModel(
            name='JudgeCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_count', models.PositiveSmallIntegerField(default=0)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('stdev', models.FloatField(blank=True, null=True)),
                ('shrink_weight', models.FloatField(blank=True, null=True)),
                ('flat', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_count', models.PositiveSmallIntegerField(default=0)),
                ('raw_mean', models.FloatField(blank=True, null=True)),
                ('normalized_mean', models.FloatField(blank=True, null=True)),
                ('rank_raw', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_normalized', models.PositiveIntegerField(blank=True, null=True)),
                ('community_score', models.FloatField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=60)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.event')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='events.project')),
            ],
            options={
                'ordering': ['rank_normalized', 'rank_raw', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Judging rubric', max_length=120)),
                ('scale_min', models.PositiveSmallIntegerField(default=1)),
                ('scale_max', models.PositiveSmallIntegerField(default=5)),
                ('instructions', models.TextField(blank=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='judging.rubric')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.judgeassignment')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.criterion')),
            ],
        ),
        migrations.AddIndex(
            model_name='judgeassignment',
            index=models.Index(fields=['event', 'judge', 'status'], name='judging_jud_event_i_1a22ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='judgeassignment',
            constraint=models.UniqueConstraint(fields=('judge', 'project'), name='uniq_judge_project'),
        ),
        migrations.AddConstraint(
            model_name='judgecalibration',
            constraint=models.UniqueConstraint(fields=('event', 'judge'), name='uniq_calibration'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.UniqueConstraint(fields=('rubric', 'key'), name='uniq_criterion_key'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('assignment', 'criterion'), name='uniq_score_per_criterion'),
        ),
    ]
