# Generated by Django 5.2.17 on 2026-09-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectresult',
            options={'ordering': [models.OrderBy(models.F('rank_normalized'), nulls_last=True), models.OrderBy(models.F('rank_raw'), nulls_last=True), 'id']},
        ),
    ]
