# Generated by Django 5.2.17 on 2026-09-27 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0002_alter_projectresult_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectresult',
            options={'ordering': [models.OrderBy(models.F('rank'), nulls_last=True), models.OrderBy(models.F('rank_normalized'), nulls_last=True), 'id']},
        ),
        migrations.AddField(
            model_name='judgecalibration',
            name='shrunk_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judgecalibration',
            name='shrunk_stdev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='adjusted_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='criterion_means',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rubric',
            name='jury_k',
            field=models.PositiveSmallIntegerField(blank=True, help_text="How many reviews the panel mean counts for when a project has few. Empty uses the event's reviews per project; 0 switches the adjustment off.", null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Jury-size adjustment'),
        ),
    ]
