# Generated by Django 5.2.17 on 2026-09-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0003_alter_projectresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresult',
            name='jury_k',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
