# Generated by Django 5.2.17 on 2026-09-27 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_theme_accent_event_theme_ground_and_more'),
        ('judging', '0004_projectresult_jury_k'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresult',
            name='pairwise_n',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='pairwise_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='pairwise_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='pairwise_wins',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rubric',
            name='pairwise',
            field=models.BooleanField(default=False, help_text='Also ask each judge which of two of their projects is the better one.', verbose_name='Pairwise comparisons'),
        ),
        migrations.CreateModel(
            name='PairwiseComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.project')),
                ('preferred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.project')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.project')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'judge'], name='judging_pai_event_i_2a69ca_idx')],
                'constraints': [models.UniqueConstraint(fields=('judge', 'left', 'right'), name='uniq_comparison_per_judge'), models.CheckConstraint(condition=models.Q(('left__lt', models.F('right'))), name='comparison_left_before_right')],
            },
        ),
    ]
