"""Print docs/normalization-evidence.md.

    python manage.py normalization_evidence sample-hack-2026 > docs/normalization-evidence.md

Two parts. Simulated events, where the true order is known, say whether the
method finds it better than an average does. The fixture set, where it is
not known, says how much the order depends on any one judge and how far each
place can be trusted. The numbers are printed as they come out.
"""

from __future__ import annotations

from django.core.management.base import BaseCommand, CommandError

from events.models import Event, EventRole, Project, Role
from judging import evidence
from judging.export import md_cell
from judging.normalization import normalize
from judging.services import collect_reviews, ensure_rubric


class Command(BaseCommand):
    help = "Print the evidence document for the normalization method."

    def add_arguments(self, parser):
        parser.add_argument("slug")
        parser.add_argument("--runs", type=int, default=300)

    def handle(self, *args, **options):
        event = Event.objects.filter(slug=options["slug"]).first()
        if event is None:
            raise CommandError(f"no event with slug {options['slug']}")
        runs = max(1, min(5000, options["runs"]))
        out = self.stdout.write

        out("# Normalization evidence")
        out("")
        out("Generated by `manage.py normalization_evidence`. Nothing here is written by hand, and")
        out("nothing was left out because it was unflattering.")
        out("")
        out("## 1. Does the method find the true order?")
        out("")
        out("On real marks nobody knows the true order. So we simulate events in which we do: each")
        out("project is given a true quality, each judge a habit (how generous, how wide a scale),")
        out("and marks are made from both, with noise, rounded to whole numbers from 1 to 5 on three")
        out("criteria. Every method sees the same marks. The code is `judging/evidence.py`.")
        out("")
        out(f"{runs} simulated events per panel, 40 projects, 30 judges, the same seeds for every method.")
        out("")
        out(
            "- **Agreement** is Kendall's tau between the method's order and the true order: 1 is the same order, 0 is no relation."
        )
        out("- **Top three found** is the share of the true best three that the method puts in its best three.")
        out("- **Winner found** is how often the truly best project is ranked first.")
        out("- **Places off** is how many places a project stands from where it belongs, on average.")
        out(
            "- **Beats the raw mean** is the share of events in which the method's agreement is higher than the raw mean's."
        )
        out("")
        verdicts = []
        for panel in evidence.PANELS:
            rows = evidence.trial(panel, runs=runs)
            out(f"### {panel.name}")
            out("")
            out(panel.says)
            out("")
            out("| method | agreement | top three found | winner found | places off | beats the raw mean |")
            out("|---|---:|---:|---:|---:|---:|")
            for key, label in evidence.METHODS:
                r = rows[key]
                beats = "" if key == "raw" else f"{r['beats_raw']:.0%}"
                out(f"| {label} | {r['tau']:.3f} | {r['top']:.0%} | {r['winner']:.0%} | {r['off']:.2f} | {beats} |")
            out("")
            gain = rows["adjusted"]["tau"] - rows["raw"]["tau"]
            verdicts.append((panel.name, gain, rows["adjusted"]["tau"] - rows["zshrunk"]["tau"]))
        out("### What the tables say")
        out("")
        for name, over_raw, over_plain in verdicts:
            how = "better than" if over_raw > 0.002 else "worse than" if over_raw < -0.002 else "level with"
            plain = "better than" if over_plain > 0.002 else "worse than" if over_plain < -0.002 else "level with"
            out(
                f"- **{name}**: the ranking score is {how} the raw mean ({over_raw:+.3f} in agreement) "
                f"and {plain} standard scores per judge ({over_plain:+.3f})."
            )
        out("")
        out("Where judges have habits, correcting for them brings the order closer to the truth, and")
        out("the more so the stronger the habits. Where they have none, there is nothing to gain, and")
        out("the last table shows what the correction costs in that case. An organizer who is sure")
        out("of a panel without habits should rank on the raw mean, which the results page shows")
        out("beside the other two. We have not met that panel.")
        out("")
        out("Standard scores per judge are what this portal used until the second day of the event.")
        out("These tables are why it no longer does. A judge with three or four reviews has a mean")
        out("that says as much about the projects they drew as about them; reading each score")
        out("against that mean corrects the judge for the luck of the draw.")
        out("")
        out("### The constant K")
        out("")
        out("A judge's leniency is pulled toward zero as if K reviews at no leniency had been seen")
        out("as well. The portal uses K = 1. It was chosen on the panels above, which is the wrong")
        out("way round if the tables are read as a test of it; here is what other values give, so")
        out("that the choice can be judged. Agreement with the true order, ranking score:")
        out("")
        values = (0.5, 1.0, 1.5, 2.0, 3.0, 6.0)
        out("| panel | " + " | ".join(f"K = {k:g}" for k in values) + " |")
        out("|---|" + "---:|" * len(values))
        for panel in evidence.PANELS:
            row = evidence.constants(panel, values, runs=runs)
            out(f"| {panel.name} | " + " | ".join(f"{row[k]:.3f}" for k in values) + " |")
        out("")
        out("A small K believes the judges' habits sooner, which pays when they are strong and costs")
        out("when there are none. K = 1 gives up little in either direction.")
        out("")

        rubric = ensure_rubric(event)
        reviews, _, _ = collect_reviews(event)
        if not reviews:
            out("## 2. The fixture set")
            out("")
            out("This event has no submitted reviews.")
            return
        result = normalize(reviews, rubric.scale_min, rubric.scale_max)
        titles = {str(p.id): p.title for p in Project.objects.filter(event=event)}
        names = {
            str(r.user_id): (r.external_id or r.user.get_username())
            for r in EventRole.objects.filter(event=event, role=Role.JUDGE).select_related("user")
        }

        out(f"## 2. {event.name}: how much does the order depend on one judge?")
        out("")
        out("Each judge is taken out in turn and the event is ranked again without them. If one")
        out("judge could move the podium, the organizer should know which one.")
        out("")
        rows = evidence.leave_one_out(reviews, rubric.scale_min, rubric.scale_max)
        rows.sort(key=lambda r: (-r["largest"], -r["mean"], r["judge"]))
        worst = rows[0]
        kept = sum(1 for r in rows if r["top_kept"] == 3)
        out(f"- Judges: {len(rows)}. Reviews: {len(reviews)}. Projects ranked: {len(result.projects)}.")
        out(f"- The first three stay the first three without {kept} of the {len(rows)} judges.")
        out(
            f"- The judge the order depends on most is {md_cell(names.get(worst['judge'], worst['judge']))}: "
            f"without them one project moves {worst['largest']} places."
        )
        out("")
        out("| judge | reviews | largest move | mean move | of the first three, kept | projects left unranked |")
        out("|---|---:|---:|---:|---:|---:|")
        for r in rows[:10]:
            out(
                f"| {md_cell(names.get(r['judge'], r['judge']))} | {r['reviews']} | {r['largest']} | "
                f"{r['mean']:.2f} | {r['top_kept']} of 3 | {r['dropped']} |"
            )
        out("")
        out("The ten judges with the most influence are shown.")
        out("")

        out(f"## 3. {event.name}: how far can a place be trusted?")
        out("")
        out("For every project, the best and the worst place it takes when any one judge is taken")
        out("out. A place that holds whoever is missing can be trusted. One that swings rests on a")
        out("single opinion, and that is nearly always a project with two reviews.")
        out("")
        spans = evidence.places_without_one_judge(reviews, rubric.scale_min, rubric.scale_max)
        out("| place | project | reviews | adjusted | place without any one judge |")
        out("|---:|---|---:|---:|---|")
        ordered = sorted(result.projects.values(), key=lambda p: (p.rank, p.project_id))
        for p in ordered[:12]:
            span = spans[p.project_id]
            out(
                f"| {p.rank} | {md_cell(titles.get(p.project_id, p.project_id))} | {p.n} | {p.adjusted:.3f} | "
                f"{span['best']} to {span['worst']} |"
            )
        out("")

        def width(p):
            return spans[p.project_id]["worst"] - spans[p.project_id]["best"]

        few = [width(p) for p in ordered if p.informative <= 2]
        many = [width(p) for p in ordered if p.informative >= 4]
        out(
            f"- Over all {len(ordered)} projects a place moves {sum(map(width, ordered)) / len(ordered):.1f} places at most, on average."
        )
        if few and many:
            out(
                f"- Projects resting on two opinions or fewer: {sum(few) / len(few):.1f} places. "
                f"On four or more: {sum(many) / len(many):.1f}."
            )
        out("")
        out("The first twelve places are shown. Where places are close and reviews are few, the")
        out("order of neighbours is not settled by the marks alone, under this method or any other.")
        out("That is an argument for another review, which is what the organizer's *Reviews per")
        out("project* list is for.")
